const renderGunPage = [
    {
        id: 1,
        category: "MELEE",
        weapon: "TACTICAL KNIFE",
    },
    {
        id: 2,
        category: "SIDEARM",
        weapon: "CLASSIC",
    },
    {
        id: 3,
        category: "SIDEARM",
        weapon: "SHORTY",
    },
    {
        id: 4,
        category: "SIDEARM",
        weapon: "FRENZY",
    },
    {
        id: 5,
        category: "SIDEARM",
        weapon: "GHOST",
    },
    {
        id: 6,
        category: "SIDEARM",
        weapon: "SHERIFF",
    },
    {
        id: 7,
        category: "SMGS",
        weapon: "STINGER",
    },
    {
        id: 8,
        category: "SMGS",
        weapon: "SPECTRE",
    },
    {
        id: 9,
        category: "SHOTGUNS",
        weapon: "BUCKY",
    },
    {
        id: 10,
        category: "SHOTGUNS",
        weapon: "JUDGE",
    },
    {
        id: 11,
        category: "RIFLES",
        weapon: "BULLDOG",
    },
    {
        id: 12,
        category: "RIFLES",
        weapon: "GUARDIAN",
    },
    {
        id: 13,
        category: "RIFLES",
        weapon: "PHANTOM",
    },
    {
        id: 14,
        category: "RIFLES",
        weapon: "VANDAL",
    },
    {
        id: 15,
        category: "SNIPER",
        weapon: "MARSHAL",
    },
    {
        id: 16,
        category: "SNIPER",
        weapon: "OUTLAW",
    },
    {
        id: 17,
        category: "SNIPER",
        weapon: "OPERATOR",
    },
    {
        id: 18,
        category: "HEAVY",
        weapon: "ARES",
    },
    {
        id: 19,
        category: "HEAVY",
        weapon: "ODIN",
    },
]
const frenzydata = [
    {
        id: 1,
        name: "Horizon",
        price: 1275,
        image: "horizon.jpg",
        guntypeid: 1,
    },
    {
        id: 2,
        name: "Celestial",
        price: 1775,
        image: "celestial.jpg",
        guntypeid: 1,
    },
    {
        id: 3,
        name: "Elderflame",
        price: 2475,
        image: "elderflame.jpg",
        guntypeid: 1,
    },
    {
        id: 4,
        name: "Prime 2.0",
        price: 1775,
        image: "prime.jpg",
        guntypeid: 1,
    },
    {
        id: 5,
        name: "Glitchpop",
        price: 2170,
        image: "glitchpop.jpg",
        guntypeid: 1,
    },
    {
        id: 6,
        name: "Origin",
        price: 1775,
        image: "origin.jpg",
        guntypeid: 1,
    },
    {
        id: 7,
        name: "Rush",
        price: 875,
        image: "rush.jpg",
        guntypeid: 1,
    },
    {
        id: 8,
        name: "RGX 11Z Pro",
        price: 2175,
        image: "rgx-11z-pro.jpg",
        guntypeid: 1,
    },
    {
        id: 9,
        name: "Nunca Olvidados",
        price: 1275,
        image: "nunca-olvidados.jpg",
        guntypeid: 1,
    },
    {
        id: 10,
        name: "Sensation",
        price: 875,
        image: "sensation.jpg",
        guntypeid: 1,
    },
    {
        id: 11,
        name: "BlastX",
        price: 2175,
        image: "blastx.jpg",
        guntypeid: 1,
    },
    {
        id: 12,
        name: "Team Ace",
        price: 1275,
        image: "team-ace.jpg",
        guntypeid: 1,
    },
    {
        id: 13,
        name: "Titanmail",
        price: 1275,
        image: "titanmail.jpg",
        guntypeid: 1,
    },
    {
        id: 14,
        name: "Xenohunter",
        price: 1775,
        image: "xenohunter.jpg",
        guntypeid: 1,
    },
    {
        id: 15,
        name: "Sarmad",
        price: 1275,
        image: "sarmad.jpg",
        guntypeid: 1,
    },
    {
        id: 16,
        name: "Ion 2.0",
        price: 1775,
        image: "ion-2.0.jpg",
        guntypeid: 1,
    },
]
