const frenzydata = [
    {
        id: 1,
        name: "Horizon",
        price: 1275,
        category: "RIFLES",
        image: "horizon.jpg",
    },
    {
        id: 2,
        name: "Celestial",
        price: 1775,
        category: "NIPERS",
        image: "celestial.jpg",
    },
    {
        id: 3,
        name: "Elderflame",
        price: 2475,
        category: 'HEAVIES',
        image: "elderflame.jpg",
    },
    {
        id: 4,
        name: "Prime 2.0",
        price: 1775,
        category: "ELEE",
        image: "prime.jpg",
    },
    {
        id: 5,
        name: "Glitchpop",
        price: 2170,
        category: 'SIDEARMS',
        image: "glitchpop.jpg",
    },
    {
        id: 6,
        name: "Origin",
        price: 1775,
        category: 'SHOTGUN',
        image: "origin.jpg",
    },
    {
        id: 7,
        name: "Rush",
        price: 875,
        category: 'SMGS',
        image: "rush.jpg",
    },
    {
        id: 8,
        name: "RGX 11Z Pro",
        price: 2175,
        category: 'SIDEARMS',
        image: "rgx-11z-pro.jpg",
    },
    {
        id: 9,
        name: "Nunca Olvidados",
        price: 1275,
        category: 'SIDEARMS',
        image: "nunca-olvidados.jpg",
    },
    {
        id: 10,
        name: "Sensation",
        price: 875,
        category: 'SIDEARMS',
        image: "sensation.jpg",
    },
    {
        id: 11,
        name: "BlastX",
        price: 2175,
        category: 'SIDEARMS',
        image: "blastx.jpg",
    },
    {
        id: 12,
        name: "Team Ace",
        price: 1275,
        category: 'SIDEARMS',
        image: "team-ace.jpg",
    },
    {
        id: 13,
        name: "Titanmail",
        price: 1275,
        category: 'SIDEARMS',
        image: "titanmail.jpg",
    },
    {
        id: 14,
        name: "Xenohunter",
        price: 1775,
        category: 'SIDEARMS',
        image: "xenohunter.jpg",
    },
    {
        id: 15,
        name: "Sarmad",
        price: 1275,
        category: 'SIDEARMS',
        image: "sarmad.jpg",
    },
    {
        id: 16,
        name: "Ion 2.0",
        price: 1775,
        category: 'SIDEARMS',
        image: "ion-2.0.jpg",
    },
]
